# Generated by Django 4.2.2 on 2023-06-22 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data_atualizacao', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('preco', models.FloatField()),
                ('instituicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investments.instituicao')),
            ],
        ),
    ]
