# Generated by Django 4.2.2 on 2023-07-26 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_acao_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAcao',
            fields=[
                ('id_aplicacao', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('data_atualizacao', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('preco', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.instituicao')),
            ],
        ),
    ]
